In [1]:
import numpy as np
import torch
x=torch.ones(2,2,requires_grad=True)
y=x+2
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [2]:
z=y*y*3
out=z.mean()
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [3]:
x = torch.tensor([330, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)



tensor([[660.,   4.],
        [  6.,   8.]], grad_fn=<ViewBackward0>)


In [4]:
z.backward(torch.tensor([[1.0,0.1],[0.01,0.001]]))
print(x.grad)


tensor([2.0000, 0.2000, 0.0200, 0.0020])
